import Head from "next/head";
import { authState } from "@/atmos/authModalAdon";
import { profile } from "@/constants/axios/apis";
import { Inter } from "next/font/google";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useRecoilState } from "recoil";
import Dashboard from "./Dashboard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const [authStateStatus, setAuthStateStatus] = useRecoilState(authState);
  const token: any = router?.query?.t;
  const location: any = router?.query?.l;
  const role: any = router?.query?.d;
  useEffect(() => {
    if (token != undefined && token != "")
      profile(atob(token)).then((response: any) => {
        if (response?.status == 200 && response?.data?.errorCode == 0) {
          setAuthStateStatus({
            loggedIn: true,
            username: response?.data?.data?.first_name,
            data: { access_token: token, userProfile: response?.data?.data },
          });
          setTimeout(() => {
            router.push("/");
          }, 2000);
        } else if (response?.status == 200 && response?.data?.errorCode == 1) {
        } else {
        }
      });
  }, [token]);
  return (
    <>
      <Head>
        <title>RealCube</title>
        <meta name="description" content="Generated by RealCube" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Dashboard />
      </main>
    </>
  );
}
