
import Layout from "@/components/layout";
import HomePage from "./home/index";
import { useRecoilValue } from "recoil";
import { authState } from "@/atmos/authModalAdon";
import axios from "axios";

import * as _redux from "@/constants"
export default function Home() {
    const authStateStatus = useRecoilValue(authState);
    _redux.setupAxios(axios, authStateStatus);
    return (
        // <>
        //     <Head>
        //         <title>RealCube</title>
        //         <meta
        //             name="description"
        //             content="Generated by create next app"
        //         />
        //         <meta
        //             name="viewport"
        //             content="width=device-width, initial-scale=1"
        //         />
        //         <link rel="icon" href="/favicon.ico" />
        //     </Head>
        // </>
        // <Propertylisitng />
        <HomePage />
        // ""
    );
}
